### ISSUE TITLE
vscale repository?

### ISSUE THREAD

**Issue by gregwebs** [hemanthmalla/k8s_resourceful#1]
Hi! I tried to run ./install.sh and was met with access errors.

```
Solving failure: 
	(1) failed to list versions for https://github.com/hemanthmalla/vscale: fatal: could not read Username for 'https://github.com': terminal prompts disabled
: exit status 128
	(2) failed to list versions for ssh://git@github.com/hemanthmalla/vscale: ERROR: Repository not found.
fatal: Could not read from remote repository.
```

**Comment by hemanthmalla** [comment]
Hi Greg,

Sorry about that.

Originally named the project vscale, ended up choosing a different one on github. Missed it, since I had a repo named vscale locally.

Updated the references, please try now.

**Comment by gregwebs** [comment]
Thanks, its building now!
